# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: local_services/files/TDR-2025-ABCD/
    -   id: check-merge-conflict

- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.36.4
  hooks:
    - id: djlint-reformat
      args: ["--no-function-formatting"]
    - id: djlint

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    - id: flake8

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml", "--exclude", "node_modules/*", "-r", "."]

-   repo: local
    hooks:
    -   id: safety-check
        name: Safety Check
        entry: custom_hooks/safety_check.sh
        language: system
        pass_filenames: false

- repo: https://github.com/thibaudcolas/pre-commit-stylelint
  rev: v16.18.0
  hooks:
    - id: stylelint
      additional_dependencies:
        - stylelint@^16.26.1
        - stylelint-config-standard-scss@^15.0.1
        - stylelint-selector-bem-pattern@^4.0.1

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
    - id: prettier
      types_or: [css, javascript, scss]
      args: ['--write']
